### PR TITLE
Adding unit tests for basic functions

### PR DESCRIPTION
**Pull request by jblom**
related to: https://github.com/beeldengeluid/beng-lod-server/issues/189

### CODE REVIEW

**Comment by jblom** [comment]
@wmelder ok will check that out. Tip: switch all code to your Ubuntu fs :-) makes life much easier

**Comment by wmelder** [comment]
@jblom het relatieve file path wordt als location parameter aan parse meegegeven: 
```
    if os.path.exists(location):
        location = pathlib.Path(location).absolute().as_uri()
```
data path is relatief tov de huidige dir. dat is de unit_test dir... op één of andere manier moet dat dus relatief aan de repo dir worden

>switch all code to your Ubuntu fs :-) makes life much easier

ja hoor, met alle plezier

**Comment by wmelder** [comment]
@jblom I pushed a fix, but I guess you probably don't want libraries git and pathlib to be added.

**Comment by jblom** [comment]
@wmelder for now it's fine. I've added the GitPython to the pipfiles now. If you're ok with it, just merge

**Review by wmelder — APPROVED** [review]
looks good.

**Pull request merged**
