### PR TITLE
showbrowse now modelled as schema:conditionsOfAccess

### PR DESCRIPTION
**Pull request by mwigham**
@wmelder could you test this please?

- [x] Check out the branch and run the beng-lod-server
- [x] Test with a few example programs and see if the message is set correctly according to whether showbrowse is true or false
- [x] Check if the content point to in the portal by url is indeed playable or not playable
- [x] Test with a few series, seasons, logtrackitems to check these still work fine
- [x] Look if the text of the access conditions can be improved

### CODE REVIEW

**Comment by wmelder** [comment]
PROGRAMS
-------------
2102004150266633831 
2101608170156507231
2102101060291829831
=> no schema:conditionsOfAccess
OK. apparantly it serves NISV schema not SDO. It is the local settings. ;-P

When SDO is default:
2102004150266633831 =>"https://schema.org/conditionsOfAccess": "Media is not playable in the General Public Portal", "https://schema.org/url": {
        "@id": "https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2102004150266633831"
      } => inderdaad geen playable asset

2101608170156507231 => geen conditionsOfAccess, https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101608170156507231 => niet afspeelbaar

2102101060291829831 => geen conditionOfAccess, https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2102101060291829831 => niet afspeelbaar
dit ding heeft trouwens een PID: URN:NBN:NL:IN:20-PGMRA2000792656

Geselecteerd via de portal optie 'Toon alleen direct te bekijken/beluisteren media':
2101608040033668131  => "https://schema.org/conditionsOfAccess": "Media playable in the General Public Portal: True. See the item's URL.", 
https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101608040033668131 => is inderdaad afspeelbaar

https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101608160145072831?ac=dgtl&q=kunst
2101608160145072831 => "https://schema.org/conditionsOfAccess": "Media playable in the General Public Portal: True. See the item's URL.",
"https://schema.org/url": {
        "@id": "https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101608160145072831"
      } => foto wordt direct getoond.

================ showbrowse tekst
Vertalen van deze tekst is lastig:
NL: 'Toon alleen direct te bekijken/beluisteren media'
EN: 'Show only media that can be viewed/listened directly' (google translate)

NL: 'Direct te bekijken/beluisteren media'
EN: 'Instantly view/listen to media' (google translate)

Now: 'Instantly view/listen to media in the General Public Portal: True/False.' and additional: "See the item's URL."

Combined suggestion: "Instantly view/listen to media at the item's URL: True/False."

==============

SERIES
----------
deze hebben geen showbrowse/ afspeelbare media

SEASONS
---------
deze kunnen we niet voorzien van GPP URL en zijn ook niet afspeelbaar

LOGTRACKITEMS
-------------------
deze vallen in de huidige dump van de catalogus nog buiten de selectie, dus daar heb ik geen voorbeelden van

@mwigham 
- [ ] Nog even kijken naar de items zonder conditionsOfAccess:
2101608170156507231 
2102101060291829831
- [ ] Suggestie voor tekst

**Comment by mwigham** [comment]
@wmelder thanks for the review. 

The items without conditionsOfAccess simply don't have any showbrowse value in their metadata. We need to choose whether we show no information (as at present), or default to showing the no access text.

'instantly' is not necessary and sounds a bit odd. 'View/listen to media at the item's URL: True' is fine for the text when there is access. I would suggest we change the wording to something like 'Media is not available for viewing/listening online' when there is no access. I think people will be confused by  'View/listen to media at the item's URL: False'.

**Comment by wmelder** [comment]
@mwigham OK, let's just not add something if showbrowse is not available in the source data. So keep what we have.
The other text suggestions are fine with me. 'Instantly' was just a suggestion, because the portal had 'direct' in the option that filters on media that is/isn't playable. So, it is more or less the same as showbrowse. But, if we leave 'instantly' out of the message, it is fine with me.

**Comment by mwigham** [comment]
@wmelder I've updated the texts and committed them.

It's a shame that English doesn't have such a nice translation of 'direct bekijken' :)

**Review by wmelder — APPROVED** [review]

**Pull request merged**
