### PR TITLE
black code formatting and flake8 linting fixes

### PR DESCRIPTION
**Pull request by jblom**
related to: https://github.com/beeldengeluid/x-omgeving/issues/546

### CODE REVIEW

**Review by wmelder — APPROVED** [review]
I reviewed ALL changes and they are only coding style changes.

**Comment by jblom** [comment]
@wmelder ok thanks for reviewing, but why close the PR? If it is all fine, then we can merge this

**Comment by wmelder** [comment]
@jblom Sorry for closing. I thought: this is a draft PR, I close this one after approving the changes, so that a proper PR can be created. But I guess the draft PR could have just be upgraded and merged. Shall I re-open it and merge?

**Comment by wmelder** [comment]
done it already

**Comment by jblom** [comment]
@wmelder nice! This is now the first repo with complete PEP8 formatting.

**Pull request merged**
