### PR TITLE
#122 sparql hdt

### PR DESCRIPTION
**Pull request by wmelder**
@jblom I guess you are the right person to test this. Mari should also be able to do this, if she were not on Windows. 

So, without having to host a triple store, we can provide a SPARQL endpoint using HDT and rdflib-hdt. I added this as an API on top of the beng-lod server, but the code can be implemented on the search API code as well. This feature needs rdflib-hdt. 

## Checkout the branch
- [x] git checkout #122_sparql_hdt

## Install rdflib-hdt
Have a look at the [documentation](https://pypi.org/project/rdflib-hdt/)
During installation you will find out that it needs pybind11 to be installed as prerequisite:
```pip install pybind11```

NOTE: This can easily be added on Linux, but not for Windows. Unfortunately, attempts to to install the VistualStudio C++ compiler and tweaking the compiler options failed.

## Download the HDT file
- [x] scp an HDT file from zorin to your location of preference.
```scp wmelder-zorin:data/nisv/hdt/nisv_cat_daan_20210515.hdt .```

Note: This HDT contains only basic metadata on the NISV catalogue. 
Note: The schema.org version of the open data lab can be found here:
```/home/wmelder/data/nisv/hdt/nisv_cat_daan_sdo_20210617.nt.hdt```

## Change configuration
- [x] Add the HDT file location to your settings.py:     
```HDT_FILE = '/home/wmelder/data/nisv/hdt/nisv_cat_daan_sdo_20210617.nt.hdt'```

## Run the server
- [x] ```cd src && python server.py```
On the first run, the HDT index files will be created. This only needs to be done once.

## Try out the request
The server will run at localhost:5309. You can look for the /sparql/ API.
- [x] Try it out! 

## TEST
- [x] please confirm that installation is ok
- [x] please confirm that the initial request returns proper sparql results

## Add query argument to the API
We need to be able to send an argument to the server containing the query. The Sparql protocol [specification ](https://www.w3.org/TR/sparql11-protocol/#query-operation)shows what is required. In short, a query argument for a GET request.
- [x] please provide suggestions on how to implement the query parameter.

## Final thoughts
I suggest to test this on the server as soon as we have a query argument. Maybe, we might also want to experiment with configurable HDT files, but that is yet another extended feature.

### CODE REVIEW

**Comment by wmelder** [comment]
- [ ] todo: pip install rdflib-hdt on zorin

**Comment by jblom** [comment]
@wmelder check, hope to be able to check it out early next week

**Comment by wmelder** [comment]
@mwigham You can find a SPARQL endpoint for the DAAN schema.org data on http://data.rdlabs.beeldengeluid.nl/
Please feel free to try it out!

**Comment by mwigham** [comment]
Very fast for simple triple queries. But I can't run any queries with more than one triple. The pattern "<id> a schema:CreativeWork; schema:actor ?e" causes a time out, the pattern "<id> a schema:CreativeWork. <id> schema:actor ?e" a proxy error. So I can't test the performance of the query we use for the Media Suite.

**Comment by wmelder** [comment]
@mwigham @jblom 
Then I am afraid that this will not help us, because we do want a SPARQL andpoint that has full SPARQL functionality and patterns using only one triple might be useful for some scenario, but are not really helpful for the MediaSuite case. 

Next steps: 
1) prepare a separate repo for HDT, so that we can continue developing without being hindered by the limitations of HDT SPARQL querying. (still can't believe you can only query with one triple).
2) Load the data into a ClioPatria instance. This way, we do have a proper SPARQL endpoint.
3) Determine how we will disclose the endpoints for the datasets in the Open Data Lab: e.g. {dataset_id}.apis.beeldengeluid.nl/sparql or sparql.apis.beeldengeluid.nl/sparql/{dataset_id}/sparql/ or ...?

**Pull request merged**
