### PR TITLE
406 music roles

### LINKED ISSUE #406: As a linked data engineer, I want to model roles in schema.org, so we can publish them in our linked data
Tasks:
- [x] Choose a solution for modelling roles in schema.org (see inventory of options)
- [x] Implement this (in beng-lod-server for now), using the mappings to Wikidata and Uitvoeringsmedium
- [x] When using the mappings, consider how best to handle fields containing multiple values (e.g. 'zang hobo', 'zang / alt hobo')
- [x] Test

We leave RDA out of scope at present, as this will require discussion/coordination with PK.net

Acceptance criteria:
- [ ] Can run a local beng-lod-server with roles in schema.org

### PR DESCRIPTION
**Pull request by mwigham**
Test plan:
- [x] Checkout the branch 406 music roles
- [x] Run the server locally
- [x] Test with MOZ concerts, both programs and scenes. Check that roles are mapped to wikidata and um (where available) for byArtist and creator roles (which includes crew) but not for other roles such as productionCompany (these should have the roleName as simple text)
- [x] Test with some other programmes and check there are no crashes or odd results

Closes #406

### CODE REVIEW

**Comment by wmelder** [comment]
everything I checked looks fine.

**Review by wmelder — APPROVED** [review]
everything I checked looks fine.

The code is sometimes hard to understand. And the tests as well... but it works :-0 

The changes are all nicely contained in the SDORDFConcept class, that we will have to move to the lod-importer later.

**Comment by mwigham** [comment]
Great, thanks! Do you want to do the merge or shall I?

I completely agree about the code, it has grown organically and should be organised much better. I hope that when we move it to the importer that we can find some time for refactoring.

**Comment by wmelder** [comment]
Looking at the git graph, it seems we have to rebase. I will look into it.

**Pull request merged**
