### PR TITLE
Person and location queries for SPARQL endpoint

### PR DESCRIPTION
**Pull request by wmelder**
Hi Mari,

I figured this branch might be the right one for sharing SPARQL queries. If not so, please let me know.
Under src/sparql I saved two queries for some particular programs that you can actually run on the triple store (and get useful results). I think these requests are a solution to this issue. If not, please let me know. 
Note: the location query gives both reconciled locations (bound to the GTAA Geografische Namen) and blank node locations (don't know yet why these weren't picked up for reconcililation). 
Note2: the response time is reasonable for a given URI...

Hope you enjoy these answers and the issue can be closed...

### CODE REVIEW

**Comment by mwigham** [comment]
Hi @wmelder. Great that you have done this. The person query is a good solution to this issue, and also runs nice and quickly. Just wondering, why did you hardcode the program ID instead of using a grlc parameter? 

I'm afraid I don't understand the location query, it seems to me that the triple `?program nisv:hasLocation ?concept .` doesn't add anything, and also I see nothing to specify the subproperty relationship. But I notice in any case that the current version of the ontology does not relate any location properties to each other using subpropertyOf. The only candidate for this would be hasProductionCountry, as other location properties do not use the GTAA (as discussed [here](https://docs.google.com/document/d/1P5HuMlzPyzUlDTbHaDOXeZ9jU3q82rnNjtM0OuecrkM/edit#heading=h.abuhiyhutdic)). Do we want to make hasProductionCountry a subproperty of hasLocation, or are there reasons not to do so?

**Comment by wmelder** [comment]
@mwigham 
* "why did you hardcode the program ID instead of using a grlc parameter?"=> I just didn't do anuthing with grlc so far... It sounds great that it provides those, because hardcoding uri's is not a great practice of course ;-)  

* "it seems to me that the triple ?program nisv:hasLocation ?concept . doesn't add anything" => You are right. This is a bug...The triple needs to be removed... 

* "I see nothing to specify the subproperty relationship." => True. Therefor a location query using subPropertyOf is not possible given the current data model. given the current model the query can be expanded using a predicate conjunction:  ```nisv:hasLocation|nisv:hasProductionCountry|nisv:hasCountry```
Alternatively, (and I guess this solution is the best for this issue) we can query the scheme for the location predicates: 
```WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/schema> {
	?pred rdfs:range nisv:Location 
  }
  GRAPH <http://data.rdlabs.beeldengeluid.nl/cat/> {
	program:346427 ?pred ?concept
  }
  ?concept skos:prefLabel ?preflabel .
``` 

* "as other location properties do not use the GTAA"
This document doesn't mention the Country field. Isn't that also linked to the GTAA?

* If a subPropertyOf relationship is needed the rdfs scheme needs to be changed: 
The nisv:Country and nisv:ProductionCountry need to be added as rdfs:subClassOf nisv:Location. Also the nisv:hasCountry and nisv:hasProductionCountry properties need to be changed to be rdfs:subPropertyOf nisv:hasLocation properties.

* "Do we want to make hasProductionCountry a subproperty of hasLocation, or are there reasons not to do so?" => for the iMMix data I would not change it. The proposed predicate selection provides a way to query for any predicate that is bound to a location. For the DAAN data we can change the schema, even if it were only for consistency reasons. So I think we could change the DAAN schema as in the bullet above this one? Agree?


So, do you want me to change the location query, using location predicates? 
And, do I need to change the queries so that they are using grlc parameters?

**Comment by mwigham** [comment]
@wmelder I like the solution of querying the schema voor location predicates, let's try that one out. Country belongs to Nationality, which I mentioned in the document as being a strange case. I'm not quite sure what we should do with it, as while it uses the GTAA, it is not a location that has anything to do with the programme, but the country that a participant comes from. What do you think?
I agree we should wait to change hasProductionCountry in the schema until the DAAN version. 
I don't think we need to use the grlc parameters yet, let's do that when we actually use the grlc api. So all that remains for this issue is to use location predicates in the location query.

**Comment by wmelder** [comment]
@mwigham 
> Country belongs to Nationality, which I mentioned in the document as being a strange case. I'm not quite sure what we should do with it, as while it uses the GTAA, it is not a location that has anything to do with the programme, but the country that a participant comes from. What do you think?

Let's not subclass that field than (in DAAN schema). For now, it is one of the properties that has nsiv:Location as class and will be returned by the location query. When it is not desired to have these locations, we can remove them from the result list using MINUS, or, probably more easy and faster, use the predicate conjunction instead. We might add this as another solution.

> I don't think we need to use the grlc parameters yet, let's do that when we actually use the grlc api. 

Oké. It does seem to be something that we need to do soon.

> So all that remains for this issue is to use location predicates in the location query.

Done. I also merged master into this branch so it now nicely merges without commit errors :-) 

Question on the coding process: I created a pull request so you could review the code changes in this branch. If I am reading it correctly, this merge pull request will now result in all the stuff from this branch being merged into master. This is not what I intended. What do we do?

**Comment by mwigham** [comment]
@wmelder what did you intend instead? We can leave the changes on the grlc-api branch, then I just close the pull request without merging.

As a broader issue, I think we should look at the branches in the linked data related repositories and decide what to do with them. It is a bit of a jungle now, which makes it hard to know what to look at, and might also cause problems when we merge them.

**Comment by wmelder** [comment]
> We can leave the changes on the grlc-api branch, then I just close the pull request without merging.

Yes please. We keep the queries in the branch and close the pull request. That was only intended for review.

> As a broader issue, I think we should look at the branches in the linked data related repositories and decide what to do with them. It is a bit of a jungle now, which makes it hard to know what to look at, and might also cause problems when we merge them.

My suggestions:
* the HTML stories Eduardo worked on and the Ontospy stuff (it's on my todo for this sprint) can be integrated and closed. 
* We might wanna have a 'lod-server' repo where we put all the DAAN stuff. Then we can deploy the DAAN stuff in test without disturbing the current beng-lod-server.
* GRLC, I am not sure how we can 'run' a grlc api, but if would be nice if we can do that on the beng-lod-server (or the future lod-server). 
* schema.org mapping branch. I am not sure what is in this branch. Can we make this a feature branch (attach it to an issue) and merge it into master if it is finished?

What do you think?

**Comment by mwigham** [comment]
* Integrating and closing ontospy branch - yes, I agree, can you do this when you are done with your work this sprint?
* New repo for lod-server - not sure if this is the best course of action, as we won't be actively developing beng-lod-server will we? (only urgent bugfixes). Perhaps something to check with Martijn?
* The grlc api is actually run in labs-search-api, my branch name is a little misleading. The role of the beng-lod-server repository in grlc is only to store the queries that the grlc api uses. They must be in the top-level folder unfortunately, which makes it a bit messy. That is why I put them in a branch. But we could merge them, or alternatively we could set up a repository just for queries, then we don't mess up our other code.
* schema.org - this contains additional files with the mapping, nothing to do with the code (consequence of combining the schema and the server code in one repository, once we have a schema accessible online then we could consider separating them). So yes, we can merge it when it's done.

**Comment by wmelder** [comment]
closing it... the sparql queries can be used whenever the grlc api is ready

**Pull request closed without merging**
