### PR TITLE
implemented simple wemi resolution

### PR DESCRIPTION
**Pull request by wmelder**

### CODE REVIEW

**Comment by wmelder** [comment]
Fixes beeldengeluid/lod-exporter#42

**Comment by wmelder** [comment]
resolves beeldengeluid/lod-exporter#42
closes beeldengeluid/lod-exporter#42

**Review by mwigham — CHANGES_REQUESTED** [review]
I checked this out and ran the tests, all green. I also tried out both curl and the swagger api for a couple of examples, those redirect nicely, using the 302.

The only issue is that there is now no status code set when the RDF is returned. Not a serious problem as it still works, but both curl and the swagger api are then unhappy that there is no valid status code, which could confuse a user.

**Comment by wmelder** [comment]
not what I expected. Thanks for noticing. good to have these things reviewed.

**Review by mwigham — APPROVED** [review]
all fine now!

**Pull request merged**
