### PR TITLE
Opendatalab#2

### PR DESCRIPTION
**Pull request by wmelder**
* please check out the opendatalab#2 branch
* run server.py
* find out if the unittests are appropriate
* inspect the code
* maybe try some programs (not only the example id given)

note that it still needs a lot more data transformations that there are now

### CODE REVIEW

**Comment by jblom** [comment]
@wmelder hee deze heeft nog conflicts en de GH actions loopt niet goed nog: zie hier https://github.com/beeldengeluid/beng-lod-server/pull/99/checks?check_run_id=2030411645 (foutje in een test)

**Comment by mwigham** [comment]
Nice that this working! Here's my feedback:
Unit tests:
- Unit tests run without errors and are logical, they follow the steps that are done by the ODL server and also put them together which is nice
- The other LOD unit tests in the project fail, I don't know if that is relevant

Code
- The code is clear and seems logical to me. @jblom can give more technical pointers
- For readability, it would be nice to get rid of commented-out code
- Personally I'm not keen on setting parameters to a specific value such as a specific ID or doc type when the relevant input parameter is None, but I don't know what others think about that 
- It would be nice to document what the different API endpoints do
- It would be handy to update the settings-example to include the index. By the way, there is an NISV_CATALOGUE_INDEX in the settings, but the code wants an ES_INDEX, why is that?
- I would prefer namespaces to be in a config instead of in code, unless we are really, really sure we are not going to change them. And I definitely agree with the TODO to remove the hardcoded URI ;)

The API works fine for the example ID and a couple of others. But it fails for these values:

- 2101608190183414731
- 2101608200186032331
- 2101608160143786731
- 2101608190183414731

**Comment by jblom** [comment]
@mwigham @wmelder it seems there is still some stuff to do (according to Mari's review). Also there are (again) unresolved conflicts in this branch.

Let me know when Mari's points and the conflicts are resolved, so I know when to give it a short check as well (I am mostly triggered by the devopsy things, such as settings).

**Comment by wmelder** [comment]
From the review:

* The other LOD unit tests in the project fail, I don't know if that is relevant
> This is fixed. The code depended on a relative path in the config. It unittests were not run from the /src directory, the paths were wrong. Now, the code is using an Flask app-context so that it can ask for the application folder and then append the relative path there. this will always work, no matter where the server is deployed.

Code

* For readability, it would be nice to get rid of commented-out code
> I am afraid the repo is not as clean as you would like to have it. Some of the commented code is actually there to uncomment when needed. Other code in comment is added: the parts of the code that were handling the flex datastore are now in coment as well. This is because we can not use the flex store, but I didn't want to remove all the code.

* Personally I'm not keen on setting parameters to a specific value such as a specific ID or doc type when the relevant input parameter is None, but I don't know what others think about that
> That was just for test purposes. It is removed, so that it returns nothing when param is None.


* It would be nice to document what the different API endpoints do
> Yes, that would be nice. I have been struggling with Swagger UI and OpenAPI, but I haven't found a wa to present a general documentation line per endpoint. Maybe @jaap has some suggestions here?

*It would be handy to update the settings-example to include the index. By the way, there is an NISV_CATALOGUE_INDEX in the settings, but the code wants an ES_INDEX, why is that?
> It was wrong indeed. It is fixed.

* I would prefer namespaces to be in a config instead of in code, unless we are really, really sure we are not going to change them. 
> I don't see a benefit in putting namespaces in a config. The namespaces are an itegral part of the data that is handled and this server is solely for handling this data. Using the namespacemanager from rdflib package it is really easy to handle the namespaces in the code.

**Pull request closed without merging**
