### PR TITLE
Added persons, organisations, location and genre

### PR DESCRIPTION
**Pull request by mwigham**
@wmelder I've extended the mapping to persons, organisations, locations and genre. Could you test please and see if it seems to work?

### CODE REVIEW

**Comment by wmelder** [comment]
The data doesn't contain persons and locations. Looking at the loaded profile it uses [this file ](resource/schema-dot-org.ttl) as schema. Therefore, the server doesn't know that it needs to process persons, places, genres, etc.

**Comment by mwigham** [comment]
@wmelder The [committed version of the schema](https://github.com/beeldengeluid/beng-lod-server/blob/schema-org-persons-and-more/resource/schema-dot-org.ttl) does contain these concepts. Have you checked out the right branch?

**Comment by wmelder** [comment]
@mwigham indeed the branch was the problem it was cc0-schema-org instead of schema-org-persons-and-more.

**Comment by wmelder** [comment]
@mwigham Missing URI's for thesaurus concepts: 
      "https://schema.org/genre": "muziekuitvoering",
      "https://schema.org/about": "levensbeschouwingen",
The source payload does contain these notation values.

**Comment by mwigham** [comment]
Thanks, I've just committed a fix for this.
In the case of genre this does mean we are bending the schema.org model a bit, as technically genre can only have a string or URL as range, and now we have made it a sdo:Thing to be able to show the label and the URI.

**Comment by wmelder** [comment]
@mwigham skos concepts are listed as type schema.org/Thing:
    {
      "@id": "http://data.beeldengeluid.nl/gtaa/127978",
      "@type": "https://schema.org/Thing",
      "http://www.w3.org/2004/02/skos/core#prefLabel": {
        "@language": "nl",
        "@value": "Lutz, Luc"
      }
    },

**Comment by mwigham** [comment]
What should they be?

**Comment by wmelder** [comment]
skos Concepts... but if we have to stretch the definitions of schema.org we need to think about another solution.

**Comment by wmelder** [comment]
@mwigham it looks as if schmea.org/Thing has a property additionalType that indicates some other type the Thing has in some vocabulary. Sounds as a way to keep the Thing (when needed) but also indicate we have an additional type that is outside of the schema definitions.

**Comment by wmelder** [comment]
The same for Place: it should also be indicated as a skos:Concept, because that is the main type of the resource. 
    {
      "@id": "http://data.beeldengeluid.nl/gtaa/34826",
      "@type": "https://schema.org/Place",
      "http://www.w3.org/2004/02/skos/core#prefLabel": {
        "@language": "nl",
        "@value": "Ens"
      }
    },

**Comment by wmelder** [comment]
apparantly, for some concepts multiple types are already asigned:
   {
      "@id": "http://data.beeldengeluid.nl/gtaa/246482",
      "@type": [
        "https://schema.org/Person",
        "https://schema.org/Thing"
      ],
      "http://www.w3.org/2004/02/skos/core#prefLabel": {
        "@language": "nl",
        "@value": "Booij, Robert Jan"
      }
    },

**Comment by wmelder** [comment]
Voor sdo:Person geldt dat het ook een sdo:Thing is en dat je de additionalType kan gebruiken. Dit lijkt me nog wel duidelijk: 
"**An additional type for the item, typically used for adding more specific types from external vocabularies** in microdata syntax. This is a relationship between something and a class that the thing is in." 

Maar hiermee weet ik niet zo goed wat we er mee aan moeten: "In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally."

**Comment by wmelder** [comment]
so probably add another triple here: https://github.com/beeldengeluid/beng-lod-server/blob/e6b5fa61306b5f3a58e96fbb25010638d2c04608/src/models/SDORdfConcept.py#L166

self.graph.add((concept_node, RDF.type, URIRef("http://www.w3.org/2004/02/skos/core#Concept")))

**Comment by wmelder** [comment]
@mwigham Why is a counter here: https://github.com/beeldengeluid/beng-lod-server/blob/e6b5fa61306b5f3a58e96fbb25010638d2c04608/src/models/SDORdfConcept.py#L78
The code is amazing. It does provide the right outcome, but I find it hard to see where the magic happens.

**Comment by mwigham** [comment]
That is used to make sure the correct used_path is selected from the list. As multiple DAAN properties get mapped to the same schema property, I need to keep track of which path was used.

I will work on some documentation for the code, also happy to talk through it with you.

**Comment by wmelder** [comment]
@mwigham simply thought it was best to merge the gpp landing page change with you schema persons branch... if all fits well we merge this one with master.

**Comment by wmelder** [comment]
@mwigham I am wondering whether it is a good idea to subClass the sdo:Place class to skos:Concept. It feels that if we subclass it in our schema mapping, we bend the rules a bit for the schema.org mapping. Instead, we might use the sdo:additionalType property to indicate the sdo:Place is (in our data) also something else (a skos:Concept).  What do you think?

sdo:Place rdf:type rdfs:Class ;
             rdfs:subClassOf sdo:Thing ;
             rdfs:subClassOf skos:Concept .

**Comment by wmelder** [comment]
@mwigham Is it so that you sub-classed the Thing class to skos:Concept to be able to add that as range to the sdo:genre property? What about sdo:Person and sdo:Organization. Yet they are not recognized as skos:Concepts. I am wondering whether sub-classing is the right mechanism here. The reason is that a sdo:Person is really much more a description of a person that is the skos:Concept that is more the description of the notion of a person.  I don't want to make things complicated, but this issue seems quite fundamental. 

###  https://schema.org/contributor - used for guests
sdo:contributor rdf:type rdf:Property ;
                rdfs:domain sdo:Thing ;
                rdfs:range sdo:Person .

###  https://schema.org/productionCompany
sdo:productionCompany rdf:type rdf:Property ;
                rdfs:domain sdo:Thing ;
                rdfs:range sdo:Organization .

**Comment by mwigham** [comment]
@wmelder I've added the skos concept as additionalType and also refactored the code to use a function for adding skos concepts. Can you test it please and see if it produces good RDF for persons, places and organisations? If you're happy then we can close this pull request.

**Comment by wmelder** [comment]
@mwigham I have another question: the [mapping ](resource/daan-mapping-schema-org.ttl) contains both MediaObject and CreativeWork. MediaObject is a subclass of CreativeWork. I was wondering why most programs have the sdo:CreativeWork and not sdo:MediaObject? Is that on purpose (for example you considered the programs to be more than a MediaObject alone), or do you think that MediaObject would be a better fit?

I suggest we fix this later in another issue. I already created a new issue for adding type information (like mime_type).

**Comment by mwigham** [comment]
MediaObject was an option, but I chose to model Program as CreativeWork and
asset item as MediaObject, that seemed a better fit given the descriptions.
But we can discuss this further.

Op ma 31 mei 2021 om 11:16 schreef Willem Melder ***@***.***>:

**Comment by mwigham** [comment]
Here is the draft mapping that I put together a while back (pre-corona!)
https://docs.google.com/spreadsheets/d/15rP7aMZj5nTrf8WFmBTgBwSIoobM7t3febRGse6rHAg/edit?usp=sharing

Op ma 31 mei 2021 om 11:19 schreef Mari Wigham ***@***.***>:

**Comment by wmelder** [comment]
Yes, we need to rethink about the draft. Let's dive into that with this issue: https://github.com/beeldengeluid/beng-lod-server/issues/120

For now, another question on the current mapping/type:  
@mwigham the additonalType seems to be OK. I noticed a creator has double sdo type:
   {
      "@id": "http://data.beeldengeluid.nl/gtaa/120400",
      "@type": [
        "https://schema.org/Person",
        "https://schema.org/Thing"
      ],
      "http://www.w3.org/2004/02/skos/core#prefLabel": {
        "@language": "nl",
        "@value": "Kooijmans, Jeanne"
      },
      "https://schema.org/additionalType": {
        "@id": "http://www.w3.org/2004/02/skos/core#Concept"
      }
    }

Is that OK? A Person is already a Thing.

**Comment by wmelder** [comment]
Ah, thanks, that's why both types are listed.

**Comment by wmelder** [comment]
@mwigham This looks good! I checked with several programs, series and seasons. The persons, locations, etc. as well as the additionalType property is working well.
I needed to fix the gpp landing page code, because season only has a landing page including the series it belongs to. This information is not available on program level, therefore the landing page is omitted when  a season is requested.
Although available, logtrackitems are not tested. But, since we are not requesting these for the Open Data lab (yet) that is no obstacle for merging this branch. Yeah!

**Pull request merged**
