### PR TITLE
Bug add publisher triple

### PR DESCRIPTION
**Pull request by wmelder**
the publisher triple is added to the resource model. For now, it fixes the absence of the triple in the current model.

In the future, the triple can be added after retrieving the resource triples from the triple store, so that we don't need to add 20M triples to the store with only the publisher property for the items.

### CODE REVIEW

**Comment by mwigham** [comment]
@wmelder The tests run fine and the code looks good. My only slight concern is the semantics of this: we are implying that Sound and Vision published the creative work - https://schema.org/publisher. When actually we are publishing the metadata about that CreativeWork only. But I don't know of any alternative that would fit the nuances. Except to put the publisher on the level of the data set, but then we lose the link at individual item level. So I would suggest we stick with this approach for now until something better comes along (if that happens).

**Comment by wmelder** [comment]
> @wmelder The tests run fine and the code looks good (due to the flexstore being down I can't actually run the server). My only slight concern is the semantics of this: we are implying that Sound and Vision published the creative work - https://schema.org/publisher. When actually we are publishing the metadata about that CreativeWork only. But I don't know of any alternative that would fit the nuances. Except to put the publisher on the level of the data set, but then we lose the link at individual item level. So I would suggest we stick with this approach for now until something better comes along (if that happens).

yes, true, formally S&V is not the rights holder or the creator of the thing. But since we publish the metadata as CC0, we should be added as publishers. The nuance is too difficult too model, I agree, so let's stick with this until (hopefully) something better passes by, like a property that describes better that we are publishing the RDF resource and not the CreativeWork.

**Comment by wmelder** [comment]
@jblom We encountered yet again the path problem with this draft. Mari provided a fix, but I think you should review that first, also because it affects the settings_exaple, that in its turn is the base for the unittests. Globally, the problem we encounter is that the tests on my computer fail because of the paths of the turtle files. When I run the server it doesn't fail. Mari encountered a failure even when running the server. So, somehow, the path to the turtle files in the config needs to be tackledd. Mari provided a [fix](https://github.com/beeldengeluid/beng-lod-server/pull/205/commits/6b93191f726dd1bde17b4659b2f5f622889050e7) Can you have a look at it?

**Comment by wmelder** [comment]
>(due to the flexstore being down I can't actually run the server). 

my local setup is using the flex store, so it is not down? Have you started the VPN?

**Comment by mwigham** [comment]
The problem was that the settings file was using https://flexstore.rdlabs.beeldengeluid.nl, which seems not to work (even with vpn). Using the prd option does work, and then I can indeed confirm that the publisher tripler appears perfectly :)

**Comment by wmelder** [comment]
> The problem was that the settings file was using https://flexstore.rdlabs.beeldengeluid.nl/, which seems not to work (even with vpn). Using the prd option does work, and then I can indeed confirm that the publisher tripler appears perfectly :)

Check. Weird that `STORAGE_BASE_URL = 'https://flexstore.rdlabs.beeldengeluid.nl'` appears to be working with me. Anyway, we will move away from querying the flex data store, so it will more stable and easier to connect (sparql endpoint doesn't require VPN) in the future.

**Comment by jblom** [comment]
@wmelder @mwigham @gb-beng to make configuring paths a bit easier (hopefully) I added 2 functions to the `base_util`. Check out the `settings_example.py` how to configure paths. The function name makes it obvious that you should define the relative path from the repo root dir. The path should work for windows and POSIX paths. 

Could you test if this works for you (both running `server.py` as well as the unit tests should just work)

**Comment by wmelder** [comment]
lijkt er op dat de configuratie truc werkt: 'C:\\Users\\wmelder\\PycharmProjects\\beng-lod-server\\resource\\daan-mapping-schema-org.ttl',

**Comment by wmelder** [comment]
nou mis ik alleen nog de publisher triple :-)

**Pull request merged**
